#! /home/nsanthony/miniconda3/bin/python
from room_finder import room_finder
from visable import visable
from do import do
from action import actions
from rooms.room_list import room_map
from people.people_list import people_list
from weapons.weapon_list import weapon_list
#from error import error

pc = people_list['pc']
pc.weapon = weapon_list['sword']
pc.armor = 4
pc.bag = {pc.weapon.name:pc.weapon}
loc = 'stone_room'
location = room_finder(loc)
location.been = 1
location = actions['look'](location)
actions['hell'](location)
[location,pc] = do(location,pc)
if room_map['skellington_room'].been > 0:
    print('got here')
    location.name = 'skellington_room'
    room_map['another_stone_room'].name = location.name
    [location,pc] = do(location,pc)



